---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-staffing-config
  labels:
    app: app-staffing
    chart: app-staffing
data:
  config.js: |
    window.env = {
      API_BASE_URL: "{{ .Values.baseURL }}",
    };
