---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      chart: {{ .Chart.Name }}
  strategy:
    type: {{ .Values.updateStrategy }}
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        chart: {{ .Chart.Name }}
      annotations:
        app: {{ .Values.appname }}
        {{- if .Values.cacheBusting.timestamp }}
        cachebusting/timestamp: {{ now }}
        {{- end }}


        {{- if .Values.prometheus }}
        {{- if .Values.prometheus.enabled }}
        prometheus.io/port: {{ .Values.prometheus.targetPort | quote }}
        prometheus.io/scrape: "true"
        {{- end }}
        {{- end }}
    spec:

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}

      {{- if and .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.appname }}
      {{- end }}

      {{- if or .Values.extraVolumes .Values.configVolumes .Values.chokidarPollerContainer.extraVolumes }}
      volumes:
      {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}

      {{- if .Values.configVolumes }}
        {{ toYaml .Values.configVolumes | nindent 8 }}
      {{- end }}

      {{- if .Values.chokidarPollerContainer.extraVolumes }}
        {{ toYaml .Values.chokidarPollerContainer.extraVolumes | nindent 8 }}
      {{- end }}
      {{- end }}

      containers:

      # Using a different container for storybook rather than
      # running two servers in the same container
      {{- if .Values.storybook.enabled }}
      - name: {{ .Values.appname }}-storybook
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}

        command: ["npm"]
        args: ["run", "storybook"]

        {{- if .Values.storybook.extraEnv }}
        env:
        {{- range $key, $value := .Values.storybook.extraEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}

        ports:
        - name: storybook
          containerPort: {{ .Values.storybook.service.targetPort }}
          protocol: TCP
      {{- end }}

      {{- if .Values.chokidarPollerContainer.enabled }}
      - name: {{ .Values.appname }}-chokidar-poller
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}

        command: ["/bin/bash"]
        args: ["/usr/src/app/chokidar-poller/start.sh"]

        {{- if .Values.chokidarPollerContainer.extraEnv }}
        env:
        {{- range $key, $value := .Values.chokidarPollerContainer.extraEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}

        {{- if or .Values.chokidarPollerContainer.extraVolumeMounts }}
        volumeMounts:
        {{- if .Values.chokidarPollerContainer.extraVolumeMounts }}
          {{ toYaml .Values.chokidarPollerContainer.extraVolumeMounts | nindent 10 }}
        {{- end }}

        {{- end }}

      {{- end }}

      - name: {{ .Values.appname }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: service
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP

        # envFrom:
        #   - secretRef:
        #       name: {{ .Values.appname }}
        {{- if .Values.extraEnv }}
        env:
        {{- range $key, $value := .Values.extraEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}

        {{- if or .Values.extraVolumeMounts .Values.configVolumeMounts }}
        volumeMounts:
        {{- if .Values.extraVolumeMounts }}
          {{ toYaml .Values.extraVolumeMounts | nindent 10 }}
        {{- end }}
        
        {{- if .Values.configVolumeMounts }}
          {{ toYaml .Values.configVolumeMounts | nindent 10 }}
        {{- end }}

        {{- end }}

        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}

        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}