{{- if .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    chart: {{ .Chart.Name }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: service
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.appname }}
    chart: {{ .Chart.Name }}
{{- end }}

{{- if and .Values.storybook.enabled .Values.storybook.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-storybook
  labels:
    app: {{ .Values.appname }}
    chart: {{ .Chart.Name }}
  {{- if .Values.storybook.service.annotations }}
  annotations:
    {{- range $key, $val := .Values.storybook.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.storybook.service.type }}
  ports:
  - name: service
    port: {{ .Values.storybook.service.port }}
    protocol: TCP
    targetPort: {{ .Values.storybook.service.targetPort }}
  selector:
    app: {{ .Values.appname }}
    chart: {{ .Chart.Name }}
{{- end }}


{{- range $index, $item := .Values.extraServices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $item.name }}
  labels:
    app: {{ $.Values.appname }}
    chart: {{ $.Chart.Name }}
  {{- if $item.annotations }}
  annotations:
    {{- range $key, $val := $item.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ $item.type }}
  ports:
  - name: service
    port: {{ $item.port }}
    protocol: TCP
    targetPort:  {{ $item.targetPort }}
  selector:
    app: {{ $.Values.appname }}
    chart: {{ $.Chart.Name }}

{{- end}}
