name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier
      - name: Depcheck
        run: npm run depcheck

      - name: Test
        run: npm run test:ci

      - name: Build App
        run: npm run build
      - name: Build Storybook
        run: npm run storybook:build

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker and Helm
        env:
          # TODO: this isn't working as expected. Output is masked.
          # AWS_ACCOUNT_NO: ${{ secrets.AWS_ACCOUNT_NO }}
          AWS_ACCOUNT_NO: "832297766686"
          ECR_REGISTRY_ID: app-staffing
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2
          PROD_TARGET_STAGE_NAME: production
          HELM_PUBLISH_S3_BUCKET: bitovi-operations-staffing-app-helm
        run: |
          echo "running scripts/ci/publish.sh"
          ./scripts/ci/publish.sh

  # https://github.com/bitovi/github-actions-bitops-ci-cd
  deploy-dev:
    # only deploy dev if not pull request
    if: github.event_name != 'pull_request'
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: bitovi/github-actions-bitops-ci-cd@0.5.0
        with:
          github-token: ${{ secrets.OPERATIONS_REPO_TOKEN }}
          org: bitovi
          repo: operations-staffing-app
          branch: main
          workflow: deploy-trigger.yaml
        env:
          API_BASE_URL: https://scaffold.bitovi-sandbox.com/api
