name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  # https://github.com/actions/github-script
  # https://octokit.github.io/rest.js/v18#actions-create-workflow-dispatch
  # https://stackoverflow.com/questions/69479400/get-run-id-after-triggering-a-github-workflow-dispatch-event
  deploy-dev:
    # only deploy dev if not pull request

    ###
    ### TODO: stop the entire job from running (not just the step)
    ### attempts:
    ###
    # attempt1: doesn't stop the job from running
    # if: ${{ github.ref }} != 'refs/heads/main'

    # attempt2: doesn't stop the job from running
    # if: ${{ github.ref != 'refs/heads/main' }}

    # attempt3: doesn't stop the job from running
    # if: env.GITHUB_EVENT_NAME != 'pull_request'

    # attempt4: doesn't stop the job from running
    # if: ${{ github.event_name }} != 'pull_request'

    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: debugging
        env:
          GITHUB_CONTEXT_EVENT_NAME: ${{ github.event_name }}
          GITHUB_CONTEXT_REF: ${{ github.ref }}
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_CONTEXT_EVENT_NAME: $GITHUB_CONTEXT_EVENT_NAME"
          echo "GITHUB_CONTEXT_REF: $GITHUB_CONTEXT_REF"
