name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: ESLint
        run: npm run eslint
      - name: Depcheck
        run: npm run depcheck
      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: "Workflow: ${{ env.GITHUB_WORKFLOW }}[bot]"
          user_email: "${{ env.GITHUB_WORKFLOW }}[bot]@workflow"
          publish_dir: ./build
