name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier
      - name: Depcheck
        run: npm run depcheck

      - name: Test
        run: npm run test:ci

      - name: Build App
        run: npm run build
      - name: Build Storybook
        run: npm run storybook:build

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: "Workflow: ${{ env.GITHUB_WORKFLOW }}[bot]"
          user_email: "${{ env.GITHUB_WORKFLOW }}[bot]@workflow"
          publish_dir: ./dist
