name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier
      - name: Depcheck
        run: npm run depcheck

      - name: Test
        run: npm run test:ci

      - name: Build App
        run: npm run build
      - name: Build Storybook
        run: npm run storybook:build